# Generated by Django 4.0.6 on 2022-08-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_created_remove_project_demo_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='_sub_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
