# Generated by Django 4.0.6 on 2022-08-27 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project__sub_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='_sub_title',
            new_name='subtitle',
        ),
    ]
