# Generated by Django 4.0.6 on 2022-08-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_rename__sub_title_project_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='source_link',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
